import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]
padding.x = 0
padding.y = 0
opacity = 1
# decorations = "None"

[font]
size = 16.0

normal.family = "JetBrains Mono"
normal.style = "Regular"

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
	{ key = "F11", action = "ToggleFullscreen" },
]
