import = ["~/.config/alacritty/catppuccin-latte.toml"]

[window]
padding.x = 10
padding.y = 10
opacity = 1

[font]
size = 16.0

normal.family = "JetBrains Mono"
normal.style = "Medium"

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F11", action = "ToggleFullscreen" },
]
