[window]
decorations = "None"
dynamic_padding = true

[font]
size = 16
offset = { y = 1 }
normal = { family = "JetBrains Mono" }
bold = { family = "JetBrains Mono" }

# Github Dark Default Colors for Alacritty

[colors.primary]
background = "#0d1117"
foreground = "#e6edf3"

# These will only be used when the `custom_cursor_colors` field is set to `true`.
[colors.cursor]
text = "#0d1117"
cursor = "#e6edf3"

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"
