[window]
decorations = "None"
dynamic_padding = true

[font]
size = 16
offset = { y = 1 }
normal = { family = "IBM Plex Mono" }

# Adwaita Alacritty Colors

# Default colors
[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#5e5c64'
red = '#e01b24'
green = '#33d17a'
yellow = '#f8e45c'
blue = '#3584e4'
magenta = '#9141ac'
cyan = '#ffa348'
white = '#deddda'

# Bright colors
[colors.bright]
black = '#77767b'
red = '#ed333b'
green = '#57e389'
yellow = '#f9f06b'
blue = '#62a0ea'
magenta = '#c061cb'
cyan = '#ffbe6f'
white = '#f6f5f4'
