[window]
decorations = "None"
padding = { x = 4, y = 0 }
dynamic_padding = true

[font]
size = 16
offset = { y = 1 }
normal = { family = "IBM Plex Mono" }

# TokyoNight STORM Alacritty Colors
# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'


# # TokyoNight DAY Alacritty Colors
# # Default colors
# [colors.primary]
# background = '#e1e2e7'
# foreground = '#3760bf'
#
# #[colors.cursor]
# #cursor = '#3760bf'
# #text = '#e1e2e7'
#
# # Normal colors
# [colors.normal]
# black = '#b4b5b9'
# red = '#f52a65'
# green = '#587539'
# yellow = '#8c6c3e'
# blue = '#2e7de9'
# magenta = '#9854f1'
# cyan = '#007197'
# white = '#6172b0'
#
# # Bright colors
# [colors.bright]
# black = '#a1a6c5'
# red = '#f52a65'
# green = '#587539'
# yellow = '#8c6c3e'
# blue = '#2e7de9'
# magenta = '#9854f1'
# cyan = '#007197'
# white = '#3760bf'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#b15c00'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#c64343'
