import = ["~/.config/alacritty/catppuccin-latte.toml"]

[window]
padding.x = 0
padding.y = 0
opacity = 1
decorations = "None"

[font]
size = 20.0

normal.family = "IBM Plex Mono"
normal.style = "Medium"

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F11", action = "ToggleFullscreen" },
]
