palette = "catppuccin_oled"

format = """
$character\
$directory\                              
[ ](bg:surface1 fg:surface0)\
$git_branch\
[ ](bg:surface2 fg:surface1)\
$git_commit\
$git_state\
$git_status\
[ ](fg:surface2)\
"""

[directory]
format = "[ $path ](bg:surface0 fg:lavender)"

[character]
format = "$symbol"
success_symbol = "[](fg:overlay2)[ ](bold bg:overlay2 fg:base)[](bg:overlay2 fg:surface0)"
error_symbol = "[](fg:peach)[ ](bold bg:peach fg:base)[](bg:peach fg:surface0)"

[git_branch]
format = "[$symbol$branch ]($style)"
symbol = " "
style = "bg:surface1 fg:teal"

[git_status]
format = "[$all_status]($style)[$ahead_behind ]($style)"
style = "bg:surface2 fg:flamingo"

[git_state]
style = "bg:yellow fg:base"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_oled]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#333333"
surface1 = "#292929"
surface0 = "#1f1f1f"
base = "#000000"
mantle = "#0a0a0a"
crust = "#141414"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
