"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$character"""

right_format = """
$git_status\
$git_branch\
$git_state\
"""

[character]
success_symbol = "[\\$](blue)"
error_symbol = "[\\$](red)"

[git_branch]
style = "bright-green"

[git_status]
style = "red"

[directory]
truncation_length = 4
style = "purple"
