format = """
$directory\
$character\
"""

right_format = """
$git_branch\
$git_commit\
$git_state\
$git_status\
"""

[directory]
style = "blue"

[character]
format = "$symbol "
success_symbol = "[󰔰](bold green)"
error_symbol = "[󰔰](bold red)"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "green"

[git_status]
style = "yellow"

[git_state]
style = "yellow"
