require 'options'

-- vim.pack.add {
--   { src = 'https://github.com/catppuccin/nvim', name = 'catppuccin' },
--   { src = 'https://github.com/nvim-treesitter/nvim-treesitter', branch = 'master', build = ':TSUpdate' },
-- }
--
-- vim.cmd.colorscheme 'catppuccin-latte'
--
-- require('nvim-treesitter.configs').setup {
--   highlight = {
--     enable = true,
--     disable = function(lang, buf)
--       local max_filesize = 100 * 1024 -- 100 KB
--       local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
--       if ok and stats and stats.size > max_filesize then
--         return true
--       end
--     end,
--   },
-- }
