gui:
  theme:
    activeBorderColor:
      - "#e08060"
      - bold

    inactiveBorderColor:
      - "#988090"

    searchingActiveBorderColor:
      - "#c8b468"
      - bold

    optionsTextColor:
      - "#80a090"

    selectedLineBgColor:
      - "#242320"

    inactiveViewSelectedLineBgColor:
      - "#1c1b19"
      - bold

    cherryPickedCommitFgColor:
      - "#d8d0c0"

    cherryPickedCommitBgColor:
      - "#b07878"

    markedBaseCommitFgColor:
      - "#80a090"

    markedBaseCommitBgColor:
      - "#c09058"

    unstagedChangesColor:
      - "#b07878"

    defaultFgColor:
      - "#d8d0c0"
