#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed base-devel git

install-yay

yay -S --needed --noconfirm --noredownload --noanswerdiff --noanswerclean --noanswerdiff --noansweredit --noanswerupgrade \
  ghostty alacritty stow \
  vim bob google-chrome \
  tmux zoxide fzf lazygit starship zed eza fd bat ripgrep jq \
  docker docker-compose docker-buildx lazydocker \
  github-cli aws-cli-v2 aws-session-manager-plugin \
  otf-monaspace otf-ibm-plex ttf-nerd-fonts-symbols noto-fonts-emoji \
  opencode claude-code \
  nodejs go \
  tree-sitter tree-sitter-cli \
  taplo-cli yaml-language-server vscode-json-languageserver \
  tinymist lua-language-server typescript-language-server \
  bash-language-server fish-lsp\
  jetbrains-toolbox

bob install nightly
bob use nightly
