source $HOME/.config/zsh/zinit.zsh
source $HOME/.config/zsh/highlight.zsh
source $HOME/.config/zsh/suggestions.zsh
source $HOME/.config/zsh/completions.zsh
source $HOME/.config/zsh/functions.zsh
source $HOME/.config/zsh/fzf.zsh
source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/eza.zsh
source $HOME/.config/zsh/plugins.zsh
source $HOME/.config/zsh/profile.zsh
source $HOME/.config/zsh/finish.zsh
