zinit snippet OMZP::asdf
zinit snippet OMZP::aws
zinit snippet OMZP::command-not-found
zinit snippet OMZP::composer
zinit snippet OMZP::dnf
zinit snippet OMZP::eza
zinit snippet OMZP::git
zinit snippet OMZP::laravel
zinit snippet OMZP::sudo
